const paths = {
  userLogin: "/login",
  verifyUser: "/confirm/:confirmationCode",
  sendConfirmEmailOneMoreTime: "/confirm/repeat-email/:email",
  userRegister: "/register",
  getAll: "/get-all",
  getAllTeachers: "/get-all-teachers",
  getAllUsersGroups: "/get-all-user-groups",
  getAllGroupErrors: "/get-all-group-errors/:id",
  getById: "/get-one-by-id/:id",
  addGroupToUser: "/add-group-to-user/:id",
  addErrorToGroup: "/add-error-to-group/:id",
  deleteGroupFromUser: "/delete-group-from-user/:id",
  deleteErrorFromGroup: "/delete-error-from-group/:id",
  addGroupToAnyUser: "/add-group-to-any-user/:id",
  create: "/add",
  updateGroupError: "/update-group-error/:id",
  updateGroupById: "/update-group-by-id/:id",
  updateById: "/update/:id",
  delete: "/delete/:id",
  uploadMedia: "/upload",
  uploadAudio: "/upload-audio",
  deleteMemberFromGroup: "/delete-group-member/:id",
  deleteLessonFromGroup: "/delete-group-lesson/:id",
  addLessonToGroup: "/add-group-lesson/:id",
  getAllGroupLessons: "/get-group-lessons/:id",
  getAllCourseNames: "/get-all-course-names",
  getWebContent: "/get-web-content",
  updateWebContent: "/update-web-content/:id",
  updatePost: "/update-post/:id",
  deletePost: "/delete-post/:id",
  deleteCategory: "/delete-category/:id",
};

export default paths;
