name: Heroku Awake

on:
  schedule:
    - cron: "*/25 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Heroku Awake
        id: heroku-awake
        uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://bairro-alto-back-end.onrender.com/web-content/get-web-content"

      - name: Check HTTP status code
        id: check-status
        run: |
          echo "${{ steps.heroku-awake.outputs.response }}"
          if [[ "${{ steps.heroku-awake.outputs.response }}" =~ "503" ]]; then
            echo "Error 503 detected. Rerunning workflow..."
            echo "retry=true" >> $RESPONSE_ENV
          else
            echo "retry=false" >> $RESPONSE_ENV
          fi

      - name: Rerun workflow
        if: env.retry == 'true'
        uses: mikeesto/heroku-awake@1.0.0
        with:
          URL: "https://bairro-alto-back-end.onrender.com/web-content/get-web-content"
